version: '2'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx/Dockerfile
    image: my-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - app1:app1
    networks:
      - nodeapp-network
  app1:
    container_name: node-server-app1
    build: 
      context: ./app
      dockerfile: app/Dockerfile
    ports:
      - "8080"
    volumes: 
      - .:/var/www/app
    working_dir: /var/www/app
    networks: 
      - nodeapp-network
networks: 
  nodeapp-network:
    driver: bridge
