version: '2'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: my-nginx:latest
    ports:
      - "80:8080"
    links:
      - app1:app1
    networks:
      - nodeapp-network
  app1:
    container_name: node-server-app1
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: nodeserverdocker_app1:latest
    links:
      - elasticsearch
    ports:
      - "8080:3000"
    volumes: 
      - .:/var/www/app
    working_dir: /var/www/app
    networks: 
      - nodeapp-network
  elasticsearch:
    image: elasticsearch
    environment:
        ELASTICSEARCH_USER: youruser
        ELASTICSEARCH_PASS: yourpw
    ports:
        - "9200:9200"
    networks: 
        - nodeapp-network
networks: 
  nodeapp-network:
    driver: overlay
    #overlay option.
