version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - app1:app1
      - app2:app2
    ports:
      - "80:80"

  app1:
    build: ./app
    environment:
    links:
      - app1
      PORT: 3000
      NODE_ENV: "production"
    ports:
      - "3000:3000"

  app2:
    build: ./app
    links:
      - app2
    environment:
      PORT: 3000
      NODE_ENV: "production"
    ports:
      - "3001:3000"
