version: '3'
services:
  app1:
      build: ./app
      environment:
          APP_NAME: "application 1"
          PORT: 3000
          NODE_ENV: "production"
  #app2:
      #consider getting nagios image.
      # environment:
      #     APP_NAME: "application 2"
      #     PORT: 3000
      #     NODE_ENV: "production"
  nginx:
      build: ./nginx
      image: my-nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      links:
        - app1:app1
      #- app2:app2